// Arte de las cartas: se usan SOLO las imagenes locales de la carpeta /img
// (creadas a mano), sin referencias externas. Si no hay imagen, se muestra emoji.
// Nombres de archivo locales: img/<id>.png (tambien acepta .jpg o .webp).
(function () {
  "use strict";
  var OU = window.OU = window.OU || {};
  OU.IMG = {
    "hop": ["img/hop.png", "img/hop.jpg", "img/hop.webp"],
    "gt": ["img/gt.png", "img/gt.jpg", "img/gt.webp"],
    "arq": ["img/arq.png", "img/arq.jpg", "img/arq.webp"],
    "pela": ["img/pela.png", "img/pela.jpg", "img/pela.webp"],
    "sat": ["img/sat.png", "img/sat.jpg", "img/sat.webp"],
    "delf": ["img/delf.png", "img/delf.jpg", "img/delf.webp"],
    "gc": ["img/gc.png", "img/gc.jpg", "img/gc.webp"],
    "mirm": ["img/mirm.png", "img/mirm.jpg", "img/mirm.webp"],
    "ant": ["img/ant.png", "img/ant.jpg", "img/ant.webp"],
    "pal": ["img/pal.png", "img/pal.jpg", "img/pal.webp"],
    "cas": ["img/cas.png", "img/cas.jpg", "img/cas.webp"],
    "tel": ["img/tel.png", "img/tel.jpg", "img/tel.webp"],
    "lan": ["img/lan.png", "img/lan.jpg", "img/lan.webp"],
    "pirit": ["img/pirit.png", "img/pirit.jpg", "img/pirit.webp"],
    "pod": ["img/pod.png", "img/pod.jpg", "img/pod.webp"],
    "mac": ["img/mac.png", "img/mac.jpg", "img/mac.webp"],
    "prt": ["img/prt.png", "img/prt.jpg", "img/prt.webp"],
    "dri": ["img/dri.png", "img/dri.jpg", "img/dri.webp"],
    "aqu": ["img/aqu.png", "img/aqu.jpg", "img/aqu.webp"],
    "her": ["img/her.png", "img/her.jpg", "img/her.webp"],
    "per": ["img/per.png", "img/per.jpg", "img/per.webp"],
    "tes": ["img/tes.png", "img/tes.jpg", "img/tes.webp"],
    "uli": ["img/uli.png", "img/uli.jpg", "img/uli.webp"],
    "ata": ["img/ata.png", "img/ata.jpg", "img/ata.webp"],
    "orf": ["img/orf.png", "img/orf.jpg", "img/orf.webp"],
    "and": ["img/and.png", "img/and.jpg", "img/and.webp"],
    "jas": ["img/jas.png", "img/jas.jpg", "img/jas.webp"],
    "hec": ["img/hec.png", "img/hec.jpg", "img/hec.webp"],
    "ajx": ["img/ajx.png", "img/ajx.jpg", "img/ajx.webp"],
    "dim": ["img/dim.png", "img/dim.jpg", "img/dim.webp"],
    "men": ["img/men.png", "img/men.jpg", "img/men.webp"],
    "bel": ["img/bel.png", "img/bel.jpg", "img/bel.webp"],
    "ene": ["img/ene.png", "img/ene.jpg", "img/ene.webp"],
    "pele": ["img/pele.png", "img/pele.jpg", "img/pele.webp"],
    "mele": ["img/mele.png", "img/mele.jpg", "img/mele.webp"],
    "anti": ["img/anti.png", "img/anti.jpg", "img/anti.webp"],
    "zus": ["img/zus.png", "img/zus.jpg", "img/zus.webp"],
    "pos": ["img/pos.png", "img/pos.jpg", "img/pos.webp"],
    "had": ["img/had.png", "img/had.jpg", "img/had.webp"],
    "ate": ["img/ate.png", "img/ate.jpg", "img/ate.webp"],
    "ars": ["img/ars.png", "img/ars.jpg", "img/ars.webp"],
    "art": ["img/art.png", "img/art.jpg", "img/art.webp"],
    "hef": ["img/hef.png", "img/hef.jpg", "img/hef.webp"],
    "apo": ["img/apo.png", "img/apo.jpg", "img/apo.webp"],
    "hera": ["img/hera.png", "img/hera.jpg", "img/hera.webp"],
    "herm": ["img/herm.png", "img/herm.jpg", "img/herm.webp"],
    "dion": ["img/dion.png", "img/dion.jpg", "img/dion.webp"],
    "dem": ["img/dem.png", "img/dem.jpg", "img/dem.webp"],
    "afr": ["img/afr.png", "img/afr.jpg", "img/afr.webp"],
    "eol": ["img/eol.png", "img/eol.jpg", "img/eol.webp"],
    "eos": ["img/eos.png", "img/eos.jpg", "img/eos.webp"],
    "iris": ["img/iris.png", "img/iris.jpg", "img/iris.webp"],
    "cro": ["img/cro.png", "img/cro.jpg", "img/cro.webp"],
    "oce": ["img/oce.png", "img/oce.jpg", "img/oce.webp"],
    "hip": ["img/hip.png", "img/hip.jpg", "img/hip.webp"],
    "jap": ["img/jap.png", "img/jap.jpg", "img/jap.webp"],
    "atl": ["img/atl.png", "img/atl.jpg", "img/atl.webp"],
    "cri": ["img/cri.png", "img/cri.jpg", "img/cri.webp"],
    "gaya": ["img/gaya.png", "img/gaya.jpg", "img/gaya.webp"],
    "our": ["img/our.png", "img/our.jpg", "img/our.webp"],
    "nix": ["img/nix.png", "img/nix.jpg", "img/nix.webp"],
    "ereb": ["img/ereb.png", "img/ereb.jpg", "img/ereb.webp"],
    "tar": ["img/tar.png", "img/tar.jpg", "img/tar.webp"],
    "teth": ["img/teth.png", "img/teth.jpg", "img/teth.webp"],
    "thes": ["img/thes.png", "img/thes.jpg", "img/thes.webp"],
    "mnem": ["img/mnem.png", "img/mnem.jpg", "img/mnem.webp"],
    "rhoa": ["img/rhoa.png", "img/rhoa.jpg", "img/rhoa.webp"],
    "phoeb": ["img/phoeb.png", "img/phoeb.jpg", "img/phoeb.webp"]
  };
})();